version: "3.1"

services:
  fix_system_php:
    build:
      context: './php'
      dockerfile: Dockerfile
    container_name: fix_system_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - 9000
    links:
      - fix_system_mysql
    environment:
      - PORT=3306
      - DB_HOST=fix_system_mysql

  fix_system_nginx:
    build:
      context: './nginx'
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - fix_system_php
    ports:
      - 7778:80
    expose:
      - 80
    
  fix_system_mysql:
    build: 
      context: './mysql'
      dockerfile: Dockerfile
    container_name: fix_system_mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    expose:
        - 3306
  